name: rick_and_morty
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  get_it: ^9.0.5
  dio: ^5.7.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_switch: ^0.3.2
  hive_ce: ^2.15.1
  hive_ce_flutter:
  flutter_svg: ^2.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  hive_ce_generator: ^1.10.0
  json_serializable: ^6.6.1
  freezed: ^3.2.3
  flutter_native_splash: ^2.4.4
  flutter_gen_runner: ^5.8.0


  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/screenshots/

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true